export const surpriseMePrompts = [
  'un fauteuil en forme d\'avocat',
  'une peinture à l\'huile surréaliste de Salvador Dalí représentant un chat jouant aux dames',
  "Des ours en peluche faisant leurs courses au Japon, ukiyo-e",
  "peinture à l'huile de Matisse représentant un robot humanoïde jouant aux échecs",
  "un panda savant fou mélangeant des produits chimiques étincelants, art numérique",
  "une macro-photo 35 mm de deux souris à Hawaï, chacune portant un petit maillot de bain et une petite planche de surf, art numérique",
  "Rendu 3D d'un joli poisson tropical dans un aquarium sur un fond bleu foncé, art numérique",
  "Un astronaute se prélassant dans une station balnéaire tropicale dans l'espace, vaporwave",
  "Portrait à la peinture à l'huile d'un capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre",
  "un vitrail représentant un hamburger et des frites",
  "un dessin au crayon et à l'aquarelle d'une ville lumineuse du futur avec des voitures volantes",
  "un salon intérieur ensoleillé avec une piscine à l'eau claire et une autre piscine à l'eau rose pastel translucide, près d'une grande fenêtre, art numérique",
  "une diseuse de bonne aventure shiba inu lisant votre destin dans un hamburger géant, art numérique",
  "Une loutre de mer avec une boucle d'oreille en perle par Johannes Vermeer",
  "un dessin au pastel à l'huile d'un chat ennuyé dans un vaisseau spatial", 
  "une loutre de mer avec une boucle d'oreille en perle de Johannes Vermeer",
  "une peinture d'un renard dans le style de la Nuit étoilée",
  "un bol de soupe qui ressemble à un monstre tricoté en laine",
  "Un robot en peluche assis contre un mur jaune",
  "Un coucher de soleil de style synthwave au-dessus de l'eau réfléchissante de la mer, art numérique",
  "Deux tours futuristes avec un pont aérien recouvert d'un feuillage luxuriant, art numérique",
  "Rendu 3D d'une montgolfière aux couleurs de l'arc-en-ciel volant au-dessus d'un lac réfléchissant",
  "Une couverture de bande dessinée représentant un super-héros portant des écouteurs",
  "Une explosion centrée de poudre colorée sur un fond noir",
  "La photo d'un chien samoyède tirant la langue et serrant dans ses bras un chat siamois blanc",
  "La photo d'un monstre à la fourrure blanche dans une pièce violette",
  "Une photo de la sculpture de David de Michel-Ange portant des écouteurs et faisant de la musique",
  "Un samouraï à cheval sur Mars, lomographie",
  "Une Cadillac moderne et élégante roule sur la voie express Gardiner avec le centre-ville de Toronto en arrière-plan, avec un reflet de lentille, photographie de 50 mm",
  "Photographie réaliste d'une jeune femme aux yeux bleus et aux cheveux blonds",
  "Un homme debout devant une porte des étoiles menant à une autre dimension",
  "Bob l'éponge dans le projet Blair Witch",
  "Un vélociraptor travaillant à un stand de hot-dogs, lomographie",
  "Un homme marchant dans les rues animées de Kowloon la nuit, éclairé par de nombreuses enseignes lumineuses, objectif 50 mm",
  "Un barbecue vivant, dans le style d'un film d'animation Pixar",
  "Un club de danse cyborg futuriste, des néons",
  "Le film d'animation japonais Star Wars 1990, perdu depuis longtemps",
  "Un hamburger en forme de Rubik's cube, photographie professionnelle de nourriture",
  "Un hérisson Synthwave, Blade Runner Cyberpunk",
  "Un astronaute rencontrant une forme de vie extraterrestre sur une planète lointaine, photographie",
  "Un dinosaure explorant la ville du Cap, photographie",
  "Un homme tombant amoureux de son ordinateur, art numérique",
  "Photographie d'un cyborg explorant Tokyo la nuit, lomographie",
  "Dracula marchant dans les rues de New York dans les années 1920, photographie en noir et blanc",
  "Avion en ondes synthétiques",
  "Un homme déambule dans les rues pluvieuses de Tokyo, avec des enseignes lumineuses au néon, 50 mm",
  "Navette spatiale survolant la ville du Cap, art numérique",
  ];